FROM maven:3.9.9-corretto-21 AS build

WORKDIR /app

COPY /pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

FROM corretto-21-jdk-slim

WORKDIR /app

COPY --from=build /TCC/target/TCC-0.0.1-SNAPSHOT.jar .

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "TCC-0.0.1-SNAPSHOT.jar"]